### ISSUE TITLE
Question: Trying out latest api version

### ISSUE THREAD

**Issue by ken-scarf** [Haskell-OpenAPI-Code-Generator/Stripe-Haskell-Library#13]
For trying out the the latest api version without pinning the version on my stripe account, this is where I would set it right?
https://stripe.com/docs/api/versioning

```haskell
instance MonadHTTP Handler where
  httpBS req = HTTP.httpBS (HTTP.addRequestHeader "Stripe-Version" "2022-11-15" req)
```
I can't seem to make it work. It's still registering as the old api version in the stripe api logs

**Comment by joel-bach** [comment]
Hey there, I am not sure where the `Handler` type comes from you are referencing here. I am guessing that in your current implementation still the [instance](https://github.com/Haskell-OpenAPI-Code-Generator/Stripe-Haskell-Library/blob/ba4401f083ff054f8da68c741f762407919de42f/src/StripeAPI/Common.hs#L67) for `IO` is used. To make it work you probably have to create a `newtype` wrapper similar to our very own `ClientT` (see [here](https://github.com/Haskell-OpenAPI-Code-Generator/Stripe-Haskell-Library/blob/ba4401f083ff054f8da68c741f762407919de42f/src/StripeAPI/Common.hs#L79)) and implement the instance there. Maybe this is already what you are doing but then some context is missing in your question.

Another option would be to misuse the `SecurityScheme` (see [here](https://github.com/Haskell-OpenAPI-Code-Generator/Stripe-Haskell-Library/blob/ba4401f083ff054f8da68c741f762407919de42f/src/StripeAPI/Common.hs#L144)) as you are free to modify requests in there. You can define a "setStripeVersion" security scheme (which both sets your API token and the version header), wrap it in the [Configuration](https://github.com/Haskell-OpenAPI-Code-Generator/Stripe-Haskell-Library/blob/ba4401f083ff054f8da68c741f762407919de42f/src/StripeAPI/Common.hs#L112) and pass it to the call of endpoints.

Hope that helps :slightly_smiling_face:

**Comment by ken-scarf** [comment]
That definitely helps! Thanks!
