### ISSUE TITLE
Release new hackage version

### ISSUE THREAD

**Issue by tysonzero** [Haskell-OpenAPI-Code-Generator/Stripe-Haskell-Library#5]
The current latest hackage version [doesn't really support Events](https://hackage.haskell.org/package/stripeapi-0.1.0.2/docs/StripeAPI-Types-NotificationEventData.html#t:NotificationEventDataObject-39-).

Currently I will install via GitHub, but it'd be great to be able to use Hackage.

**Comment by joel-bach** [comment]
Hi there

I updated the version on the Hackage and on GitHub to use the latest version of the Stripe specification and of the generator (https://github.com/Haskell-OpenAPI-Code-Generator/Stripe-Haskell-Library/pull/6).

As you surely have noticed, the generated code is quite big and needs quite a lot of time to compile. I would recommend you to use the generator (https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator) directly to generate only the code you actually need. If you are a nix user, you can use this: https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/blob/master/nix/generate-client.nix

You can find a usage of this here: https://github.com/NorfairKing/smos/blob/release/nix/overlay.nix#L232

Please let me know if this works for you so I can close the issue.

**Comment by tysonzero** [comment]
New hackage version works great! Thanks! Good to note, will check that out in future if compile times become an issue.

**Comment by joel-bach** [comment]
Perfect, glad to hear!
